Don't log exceptions if Task/Future "cancel()" method was called.
